extends: airbnb
installedESLint: true
plugins:
  - react
  - jsx-a11y
  - import
env:
  browser: true
rules:
  react/sort-comp: 0
  no-shadow: 0
  semi:
    - 1
    - never
  class-methods-use-this: 0
  import/prefer-default-export: 0
  react/jsx-filename-extension: 0
  react/require-extension: 0
  react/no-unused-prop-types:
    - 2
    - skipShapeProps: true
